
openapi: v3.0.3
info:
  title: Bolt Machine
  license:
    name: MIT
    url: https://mit-license.org/
  version: 1.0.9
servers:
  - url: http://localhost:3001
  - url: http://localhost:3002
  - url: http://localhost:3003
tags:
  - name: Channels
    description: APIs to perform operations related to LN channels
  - name: Peers
    description: APIs to perform operations related to LN peers
  - name: Payments
    description: APIs to perform operations related to LN payments
  - name: Invoices
    description: APIs to perform operations related to LN invoices
  - name: On-chain
    description: APIs to perform on-chain operations
  - name: LND
    description: APIs to perform RGB operations
